### ISSUE TITLE
Meta: Get initial testers and do a basic test run for all targets.

### ISSUE THREAD

**Issue by ichard26** [ichard26/black-mypyc-wheels#1]
While mypyc aims to produce safe and stable code and to support most Python code, it's not perfect. Sometimes it miscompiles some bit of code, or changes the runtime behaviour in a way that only crashes in certain situations, etc. Before mypyc-ified black can ever be shipped by default via PyPI, significantly more stability testing has to be done across all targeted environments.

- [x] Get automated wheel building up and running
- [x] Publish the wheels on a PEP 503 index so trying out the wheels is only a pip install away: https://ichard26.github.io/black-mypyc-index/
- [ ] Finish up [diff-shades](https://github.com/ichard26/diff-shades) so we can verify the mypyc wheels have no functional differences from the normal one
- [ ] Write instructions so testers know what to do
- [x] Set up some way of collecting information on how stable the wheels are on various environments (a simple Google Form should do?)

**Comment by ichard26** [comment]
Note for myself:

> Here's the diff-shades analysis file that should be used for --repeat-projects-from and during the comparison: [full.tar.gz](https://github.com/ichard26/black-mypyc-wheels/files/7445345/full.tar.gz)
>
> Here's the PEP 503 index: https://ichard26.github.io/black-mypyc-index/
